# See CI documentation: https://doc.rust-lang.org/cargo/guide/continuous-integration.html#buildssrht
image: debian/stable
packages:
    - rust
sources:
    - https://git.sr.ht/~vlnk/bookmarkt
tasks:
    - stable: |
        cd bookmarkt
        cargo build --verbose
        cargo test --verbose
