# See CI documentation: https://doc.rust-lang.org/cargo/guide/continuous-integration.html#buildssrht
image: alpine/latest
packages:
    - rustup
sources:
    - https://git.sr.ht/~vlnk/bookmarkt
tasks:
    - setup: |
        rustup toolchain install stable
        cd bookmarkt
        rustup run stable cargo fetch
    - stable: |
        rustup default stable
        cd <your project>/
        cargo build --verbose
        cargo test --verbose
